services:
    backend:
        container_name: "matcha-back"
        image: oven/bun:1.3
        networks:
            - "matcha-net"
        tty: true
        volumes:
            - "./backend:/home/bun/app"
        command: ["bash"]
        ports:
            - 81:3000

    frontend:
        container_name: "matcha-front"
        image: oven/bun:1.3
        networks:
            - "matcha-net"
        tty: true
        volumes:
            - "./frontend:/home/bun/app"
        command: ["bash"]
        ports:
            - 80:5173

    database:
        container_name: "matcha-database"
        image: postgres:18.0
        networks:
            - "matcha-net"
        volumes:
            - "db-data:/var/lib/postgresql"
        env_file: "db/.env"

    adminer:
        container_name: "matcha-adminer"
        image: adminer
        networks:
            - "matcha-net"
        ports:
            - 8080:8080

networks:
    matcha-net:
        driver: bridge

volumes:
    db-data:
