CREATE TYPE "gender" AS ENUM (
	'man',
	'woman',
	'other',
	'non_binary'
);

CREATE TYPE "sex" AS ENUM (
	'male',
	'female',
	'intersex'
);

CREATE TYPE "notification_type" AS ENUM (
	'message',
	'like',
	'profile_view',
	'unlike'
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"lastname" TEXT NOT NULL,
	"email" TEXT NOT NULL,
	"email_validated_at" TIMESTAMP,
	"password" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "users_details" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"gender" GENDER NOT NULL,
	"sex" SEX NOT NULL,
	"preferred_gender" GENDER NOT NULL,
	"preferred_sex" SEX NOT NULL,
	"preferred_min_age" INTEGER NOT NULL,
	"preferred_max_age" INTEGER NOT NULL,
	"lat" DECIMAL NOT NULL,
	"lon" DECIMAL NOT NULL,
	"biography" TEXT NOT NULL,
	"fame_rating" INTEGER NOT NULL,
	"birthday" DATE NOT NULL,
	"last_connection" TIMESTAMP,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "tags" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "users_interests_tags" (
	"id" SERIAL NOT NULL UNIQUE,
	"user_id" BIGINT NOT NULL,
	"tag_id" BIGINT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "users_photos" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"file_path" TEXT NOT NULL,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "profile_visits" (
	"id" SERIAL NOT NULL UNIQUE,
	"visitor_user_id" BIGINT NOT NULL,
	"visited_user_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "profile_likes" (
	"id" SERIAL NOT NULL UNIQUE,
	"liker_user_id" BIGINT NOT NULL,
	"liked_user_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "blocked_users" (
	"id" SERIAL NOT NULL UNIQUE,
	"blocker_user_id" BIGINT NOT NULL,
	"blocked_user_id" BIGINT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "reported_users" (
	"id" SERIAL NOT NULL UNIQUE,
	"reporter_user_id" BIGINT NOT NULL,
	"reported_user_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "messages" (
	"id" SERIAL NOT NULL UNIQUE,
	"sender_user_id" BIGINT NOT NULL,
	"receiver_user_id" BIGINT NOT NULL,
	"message" TEXT NOT NULL,
	"sent_at" TIMESTAMP NOT NULL,
	"viewed_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "notifications" (
	"id" SERIAL NOT NULL UNIQUE,
	"producer_user_id" BIGINT NOT NULL,
	"target_user_id" BIGINT NOT NULL,
	"type" NOTIFICATION_TYPE NOT NULL,
	"viewed_at" TIMESTAMP,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);



ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "users_interests_tags"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users_interests_tags"
ADD FOREIGN KEY("tag_id") REFERENCES "tags"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "users_photos"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "profile_visits"("visitor_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "profile_visits"("visited_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "profile_likes"("liker_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "profile_likes"("liked_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "blocked_users"("blocker_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "blocked_users"("blocked_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "reported_users"("reporter_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "reported_users"("reported_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "messages"("sender_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "messages"("receiver_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "notifications"("producer_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "notifications"("target_user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "users_details"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;